// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See Vrv64g_cache_system_tb.h for the primary calling header

#ifndef VERILATED_VRV64G_CACHE_SYSTEM_TB_RV64G_L1_DCACHE_H_
#define VERILATED_VRV64G_CACHE_SYSTEM_TB_RV64G_L1_DCACHE_H_  // guard

#include "verilated.h"
#include "verilated_timing.h"


class Vrv64g_cache_system_tb__Syms;

class alignas(VL_CACHE_LINE_BYTES) Vrv64g_cache_system_tb_rv64g_l1_dcache final : public VerilatedModule {
  public:

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        VL_IN8(clk_i,0,0);
        VL_IN8(rst_ni,0,0);
        VL_IN8(invalidate_all_i,0,0);
        VL_IN8(req_i,0,0);
        VL_IN8(we_i,0,0);
        VL_IN8(be_i,7,0);
        VL_OUT8(gnt_o,0,0);
        VL_OUT8(rvalid_o,0,0);
        VL_IN8(amo_i,0,0);
        VL_IN8(lr_i,0,0);
        VL_IN8(sc_i,0,0);
        VL_IN8(amo_op_i,4,0);
        VL_IN8(amo_word_i,0,0);
        VL_IN8(vlsu_req_i,0,0);
        VL_IN8(vlsu_lane_valid_i,7,0);
        VL_IN8(vlsu_lane_we_i,7,0);
        VL_OUT8(__PVT__vlsu_ready_o,0,0);
        VL_OUT8(__PVT__vlsu_done_o,0,0);
        VL_OUT8(__PVT__vlsu_lane_done_o,7,0);
        VL_OUT8(__PVT__vlsu_lane_hit_o,7,0);
        VL_OUT8(tl_a_valid_o,0,0);
        VL_IN8(tl_a_ready_i,0,0);
        VL_OUT8(tl_a_opcode_o,2,0);
        VL_OUT8(tl_a_param_o,2,0);
        VL_OUT8(tl_a_size_o,3,0);
        VL_OUT8(tl_a_source_o,3,0);
        VL_OUT8(tl_a_mask_o,7,0);
        VL_OUT8(tl_a_corrupt_o,0,0);
        VL_IN8(tl_b_valid_i,0,0);
        VL_OUT8(tl_b_ready_o,0,0);
        VL_IN8(tl_b_opcode_i,2,0);
        VL_IN8(tl_b_param_i,2,0);
        VL_IN8(tl_b_size_i,3,0);
        VL_IN8(tl_b_source_i,3,0);
        VL_IN8(tl_b_mask_i,7,0);
        VL_IN8(tl_b_corrupt_i,0,0);
        VL_OUT8(tl_c_valid_o,0,0);
        VL_IN8(tl_c_ready_i,0,0);
        VL_OUT8(tl_c_opcode_o,2,0);
        VL_OUT8(tl_c_param_o,2,0);
        VL_OUT8(tl_c_size_o,3,0);
        VL_OUT8(tl_c_source_o,3,0);
        VL_OUT8(tl_c_corrupt_o,0,0);
        VL_IN8(tl_d_valid_i,0,0);
        VL_OUT8(tl_d_ready_o,0,0);
        VL_IN8(tl_d_opcode_i,2,0);
        VL_IN8(tl_d_param_i,1,0);
        VL_IN8(tl_d_size_i,3,0);
        VL_IN8(tl_d_source_i,3,0);
        VL_IN8(tl_d_sink_i,3,0);
        VL_IN8(tl_d_denied_i,0,0);
        VL_IN8(tl_d_corrupt_i,0,0);
        VL_OUT8(tl_e_valid_o,0,0);
        VL_IN8(tl_e_ready_i,0,0);
        VL_OUT8(tl_e_sink_o,3,0);
        CData/*7:0*/ __PVT__arr_valid_way;
        CData/*7:0*/ __PVT__arr_dirty_way;
        CData/*0:0*/ __PVT__vlsu_miss_busy;
        CData/*0:0*/ __PVT__vlsu_miss_ready_for_replay;
        CData/*0:0*/ __PVT__vlsu_miss_refill_req;
        CData/*0:0*/ __PVT__vlsu_miss_refill_done;
        CData/*2:0*/ __PVT__victim_way;
        CData/*0:0*/ __PVT__plru_access_q;
        CData/*2:0*/ __PVT__plru_used_way_q;
    };
    struct {
        CData/*0:0*/ __PVT__pend_is_amo_q;
        CData/*0:0*/ __PVT__pend_is_amo_n;
        CData/*4:0*/ __PVT__pend_amo_op_q;
        CData/*4:0*/ __PVT__pend_amo_op_n;
        CData/*0:0*/ __PVT__pend_amo_word_q;
        CData/*0:0*/ __PVT__pend_amo_word_n;
        CData/*0:0*/ __PVT__resv_valid_q;
        CData/*0:0*/ __PVT__resv_valid_n;
        CData/*0:0*/ __PVT__resv_word_q;
        CData/*0:0*/ __PVT__resv_word_n;
        CData/*0:0*/ __PVT__pend_is_lr_q;
        CData/*0:0*/ __PVT__pend_is_lr_n;
        CData/*0:0*/ __PVT__pend_is_sc_q;
        CData/*0:0*/ __PVT__pend_is_sc_n;
        CData/*0:0*/ __PVT__sc_success_q;
        CData/*0:0*/ __PVT__sc_success_n;
        CData/*3:0*/ __PVT__state;
        CData/*3:0*/ __PVT__state_n;
        CData/*3:0*/ __PVT__return_state_q;
        CData/*3:0*/ __PVT__return_state_n;
        CData/*2:0*/ __PVT__beat_q;
        CData/*2:0*/ __PVT__beat_n;
        CData/*4:0*/ __PVT__pend_index_q;
        CData/*4:0*/ __PVT__pend_index_n;
        CData/*2:0*/ __PVT__pend_word_q;
        CData/*2:0*/ __PVT__pend_word_n;
        CData/*2:0*/ __PVT__pend_victim_q;
        CData/*2:0*/ __PVT__pend_victim_n;
        CData/*0:0*/ __PVT__pend_is_store_q;
        CData/*0:0*/ __PVT__pend_is_store_n;
        CData/*7:0*/ __PVT__pend_be_q;
        CData/*7:0*/ __PVT__pend_be_n;
        CData/*1:0*/ __PVT__pend_evict_state_q;
        CData/*1:0*/ __PVT__pend_evict_state_n;
        CData/*3:0*/ __PVT__pend_sink_q;
        CData/*3:0*/ __PVT__pend_sink_n;
        CData/*0:0*/ __PVT__pend_is_probe_q;
        CData/*0:0*/ __PVT__pend_is_probe_n;
        CData/*2:0*/ __PVT__pend_probe_param_q;
        CData/*3:0*/ __PVT__pend_probe_source_q;
        CData/*0:0*/ __PVT__pend_has_data_q;
        CData/*0:0*/ __PVT__pend_has_data_n;
        CData/*0:0*/ __PVT__pend_probe_hit_q;
        CData/*4:0*/ __PVT__probe_pend_index_q;
        CData/*4:0*/ __PVT__probe_pend_index_n;
        CData/*2:0*/ __PVT__probe_pend_param_q;
        CData/*2:0*/ __PVT__probe_pend_param_n;
        CData/*3:0*/ __PVT__probe_pend_source_q;
        CData/*3:0*/ __PVT__probe_pend_source_n;
        CData/*0:0*/ __PVT__probe_pend_has_data_q;
        CData/*0:0*/ __PVT__probe_pend_has_data_n;
        CData/*0:0*/ __PVT__probe_pend_hit_q;
        CData/*0:0*/ __PVT__probe_pend_hit_n;
        CData/*2:0*/ __PVT__probe_pend_way_q;
        CData/*2:0*/ __PVT__probe_pend_way_n;
        CData/*4:0*/ __PVT__binv_index;
        CData/*0:0*/ __PVT__binv_hit;
        CData/*2:0*/ __PVT__binv_way;
        CData/*2:0*/ __PVT__arr_word_sel;
        CData/*2:0*/ __PVT__arr_way_sel;
        CData/*0:0*/ __PVT__arr_write_en;
        CData/*1:0*/ __PVT__arr_state_in;
        CData/*7:0*/ __PVT__arr_be;
        CData/*4:0*/ __PVT__arr_index_w;
    };
    struct {
        CData/*0:0*/ __PVT__hit;
        CData/*2:0*/ __PVT__hit_way;
        CData/*0:0*/ __PVT__gnt_n;
        CData/*0:0*/ __PVT__rvalid_n;
        CData/*0:0*/ __PVT__plru_access_n;
        CData/*2:0*/ __PVT__plru_used_way_n;
        CData/*0:0*/ __PVT__tl_a_valid_n;
        CData/*2:0*/ __PVT__tl_a_opcode_n;
        CData/*2:0*/ __PVT__tl_a_param_n;
        CData/*3:0*/ __PVT__tl_a_size_n;
        CData/*3:0*/ __PVT__tl_a_source_n;
        CData/*7:0*/ __PVT__tl_a_mask_n;
        CData/*0:0*/ __PVT__tl_b_ready_n;
        CData/*0:0*/ __PVT__tl_c_valid_n;
        CData/*2:0*/ __PVT__tl_c_opcode_n;
        CData/*2:0*/ __PVT__tl_c_param_n;
        CData/*3:0*/ __PVT__tl_c_size_n;
        CData/*3:0*/ __PVT__tl_c_source_n;
        CData/*0:0*/ __PVT__tl_d_ready_n;
        CData/*0:0*/ __PVT__tl_e_valid_n;
        CData/*3:0*/ __PVT__tl_e_sink_n;
        CData/*0:0*/ __PVT__u_arrays__DOT__arb_bank_req__BRA__0__KET__;
        CData/*0:0*/ __PVT__u_arrays__DOT__arb_bank_we__BRA__0__KET__;
        CData/*4:0*/ __PVT__u_arrays__DOT__arb_bank_index__BRA__4__03a0__KET__;
        CData/*2:0*/ __PVT__u_arrays__DOT__arb_bank_way__BRA__2__03a0__KET__;
        CData/*7:0*/ __PVT__u_arrays__DOT__arb_bank_be__BRA__7__03a0__KET__;
        CData/*1:0*/ __PVT__u_arrays__DOT__scalar_state_r;
        CData/*7:0*/ u_arrays__DOT____Vcellout__g_bank__BRA__1__KET____DOT__u_arbiter__bank_be_o;
        CData/*2:0*/ u_arrays__DOT____Vcellout__g_bank__BRA__1__KET____DOT__u_arbiter__bank_way_o;
        CData/*4:0*/ u_arrays__DOT____Vcellout__g_bank__BRA__1__KET____DOT__u_arbiter__bank_index_o;
        CData/*0:0*/ u_arrays__DOT____Vcellout__g_bank__BRA__1__KET____DOT__u_arbiter__bank_we_o;
        CData/*0:0*/ u_arrays__DOT____Vcellout__g_bank__BRA__1__KET____DOT__u_arbiter__bank_req_o;
        CData/*7:0*/ u_arrays__DOT____Vcellout__g_bank__BRA__2__KET____DOT__u_arbiter__bank_be_o;
        CData/*2:0*/ u_arrays__DOT____Vcellout__g_bank__BRA__2__KET____DOT__u_arbiter__bank_way_o;
        CData/*4:0*/ u_arrays__DOT____Vcellout__g_bank__BRA__2__KET____DOT__u_arbiter__bank_index_o;
        CData/*0:0*/ u_arrays__DOT____Vcellout__g_bank__BRA__2__KET____DOT__u_arbiter__bank_we_o;
        CData/*0:0*/ u_arrays__DOT____Vcellout__g_bank__BRA__2__KET____DOT__u_arbiter__bank_req_o;
        CData/*7:0*/ u_arrays__DOT____Vcellout__g_bank__BRA__3__KET____DOT__u_arbiter__bank_be_o;
        CData/*2:0*/ u_arrays__DOT____Vcellout__g_bank__BRA__3__KET____DOT__u_arbiter__bank_way_o;
        CData/*4:0*/ u_arrays__DOT____Vcellout__g_bank__BRA__3__KET____DOT__u_arbiter__bank_index_o;
        CData/*0:0*/ u_arrays__DOT____Vcellout__g_bank__BRA__3__KET____DOT__u_arbiter__bank_we_o;
        CData/*0:0*/ u_arrays__DOT____Vcellout__g_bank__BRA__3__KET____DOT__u_arbiter__bank_req_o;
        CData/*7:0*/ u_arrays__DOT____Vcellout__g_bank__BRA__4__KET____DOT__u_arbiter__bank_be_o;
        CData/*2:0*/ u_arrays__DOT____Vcellout__g_bank__BRA__4__KET____DOT__u_arbiter__bank_way_o;
        CData/*4:0*/ u_arrays__DOT____Vcellout__g_bank__BRA__4__KET____DOT__u_arbiter__bank_index_o;
        CData/*0:0*/ u_arrays__DOT____Vcellout__g_bank__BRA__4__KET____DOT__u_arbiter__bank_we_o;
        CData/*0:0*/ u_arrays__DOT____Vcellout__g_bank__BRA__4__KET____DOT__u_arbiter__bank_req_o;
        CData/*7:0*/ u_arrays__DOT____Vcellout__g_bank__BRA__5__KET____DOT__u_arbiter__bank_be_o;
        CData/*2:0*/ u_arrays__DOT____Vcellout__g_bank__BRA__5__KET____DOT__u_arbiter__bank_way_o;
        CData/*4:0*/ u_arrays__DOT____Vcellout__g_bank__BRA__5__KET____DOT__u_arbiter__bank_index_o;
        CData/*0:0*/ u_arrays__DOT____Vcellout__g_bank__BRA__5__KET____DOT__u_arbiter__bank_we_o;
        CData/*0:0*/ u_arrays__DOT____Vcellout__g_bank__BRA__5__KET____DOT__u_arbiter__bank_req_o;
        CData/*7:0*/ u_arrays__DOT____Vcellout__g_bank__BRA__6__KET____DOT__u_arbiter__bank_be_o;
        CData/*2:0*/ u_arrays__DOT____Vcellout__g_bank__BRA__6__KET____DOT__u_arbiter__bank_way_o;
        CData/*4:0*/ u_arrays__DOT____Vcellout__g_bank__BRA__6__KET____DOT__u_arbiter__bank_index_o;
        CData/*0:0*/ u_arrays__DOT____Vcellout__g_bank__BRA__6__KET____DOT__u_arbiter__bank_we_o;
        CData/*0:0*/ u_arrays__DOT____Vcellout__g_bank__BRA__6__KET____DOT__u_arbiter__bank_req_o;
        CData/*7:0*/ u_arrays__DOT____Vcellout__g_bank__BRA__7__KET____DOT__u_arbiter__bank_be_o;
        CData/*2:0*/ u_arrays__DOT____Vcellout__g_bank__BRA__7__KET____DOT__u_arbiter__bank_way_o;
        CData/*4:0*/ u_arrays__DOT____Vcellout__g_bank__BRA__7__KET____DOT__u_arbiter__bank_index_o;
        CData/*0:0*/ u_arrays__DOT____Vcellout__g_bank__BRA__7__KET____DOT__u_arbiter__bank_we_o;
        CData/*0:0*/ u_arrays__DOT____Vcellout__g_bank__BRA__7__KET____DOT__u_arbiter__bank_req_o;
        CData/*1:0*/ __PVT__u_arrays__DOT__u_crossbar__DOT__state_q;
        CData/*1:0*/ __PVT__u_arrays__DOT__u_crossbar__DOT__state_n;
    };
    struct {
        CData/*7:0*/ __PVT__u_arrays__DOT__u_crossbar__DOT__pending_q;
        CData/*7:0*/ __PVT__u_arrays__DOT__u_crossbar__DOT__pending_n;
        CData/*7:0*/ __PVT__u_arrays__DOT__u_crossbar__DOT__latch_valid_q;
        CData/*7:0*/ __PVT__u_arrays__DOT__u_crossbar__DOT__latch_we_q;
        CData/*7:0*/ __PVT__u_arrays__DOT__u_crossbar__DOT__lane_grant;
        CData/*7:0*/ __PVT__u_arrays__DOT__u_crossbar__DOT__bank_active;
        CData/*7:0*/ __PVT__u_arrays__DOT__u_crossbar__DOT__bank_req_r;
        CData/*7:0*/ __PVT__u_arrays__DOT__u_crossbar__DOT__bank_we_r;
        CData/*7:0*/ __PVT__u_arrays__DOT__u_crossbar__DOT__done_q;
        CData/*7:0*/ __PVT__u_arrays__DOT__u_crossbar__DOT__done_n;
        CData/*2:0*/ __PVT__u_arrays__DOT__u_crossbar__DOT__g_bank_arb__BRA__0__KET____DOT__winner;
        CData/*0:0*/ __PVT__u_arrays__DOT__u_crossbar__DOT__g_bank_arb__BRA__0__KET____DOT__has_req;
        CData/*2:0*/ __PVT__u_arrays__DOT__u_crossbar__DOT__g_bank_arb__BRA__1__KET____DOT__winner;
        CData/*0:0*/ __PVT__u_arrays__DOT__u_crossbar__DOT__g_bank_arb__BRA__1__KET____DOT__has_req;
        CData/*2:0*/ __PVT__u_arrays__DOT__u_crossbar__DOT__g_bank_arb__BRA__2__KET____DOT__winner;
        CData/*0:0*/ __PVT__u_arrays__DOT__u_crossbar__DOT__g_bank_arb__BRA__2__KET____DOT__has_req;
        CData/*2:0*/ __PVT__u_arrays__DOT__u_crossbar__DOT__g_bank_arb__BRA__3__KET____DOT__winner;
        CData/*0:0*/ __PVT__u_arrays__DOT__u_crossbar__DOT__g_bank_arb__BRA__3__KET____DOT__has_req;
        CData/*2:0*/ __PVT__u_arrays__DOT__u_crossbar__DOT__g_bank_arb__BRA__4__KET____DOT__winner;
        CData/*0:0*/ __PVT__u_arrays__DOT__u_crossbar__DOT__g_bank_arb__BRA__4__KET____DOT__has_req;
        CData/*2:0*/ __PVT__u_arrays__DOT__u_crossbar__DOT__g_bank_arb__BRA__5__KET____DOT__winner;
        CData/*0:0*/ __PVT__u_arrays__DOT__u_crossbar__DOT__g_bank_arb__BRA__5__KET____DOT__has_req;
        CData/*2:0*/ __PVT__u_arrays__DOT__u_crossbar__DOT__g_bank_arb__BRA__6__KET____DOT__winner;
        CData/*0:0*/ __PVT__u_arrays__DOT__u_crossbar__DOT__g_bank_arb__BRA__6__KET____DOT__has_req;
        CData/*2:0*/ __PVT__u_arrays__DOT__u_crossbar__DOT__g_bank_arb__BRA__7__KET____DOT__winner;
        CData/*0:0*/ __PVT__u_arrays__DOT__u_crossbar__DOT__g_bank_arb__BRA__7__KET____DOT__has_req;
        CData/*2:0*/ u_arrays__DOT__u_crossbar__DOT____Vlvbound_h69f63477__0;
        CData/*4:0*/ u_arrays__DOT__u_crossbar__DOT____Vlvbound_hc1d0273f__0;
        CData/*2:0*/ u_arrays__DOT__u_crossbar__DOT____Vlvbound_had3e542b__0;
        CData/*2:0*/ u_arrays__DOT__u_crossbar__DOT____Vlvbound_h2d86f8f6__0;
        CData/*7:0*/ __PVT__u_arrays__DOT__g_bank__BRA__0__KET____DOT__u_bank__DOT__line_addr;
        CData/*7:0*/ __PVT__u_arrays__DOT__g_bank__BRA__1__KET____DOT__u_bank__DOT__line_addr;
        CData/*7:0*/ __PVT__u_arrays__DOT__g_bank__BRA__2__KET____DOT__u_bank__DOT__line_addr;
        CData/*7:0*/ __PVT__u_arrays__DOT__g_bank__BRA__3__KET____DOT__u_bank__DOT__line_addr;
        CData/*7:0*/ __PVT__u_arrays__DOT__g_bank__BRA__4__KET____DOT__u_bank__DOT__line_addr;
        CData/*7:0*/ __PVT__u_arrays__DOT__g_bank__BRA__5__KET____DOT__u_bank__DOT__line_addr;
        CData/*7:0*/ __PVT__u_arrays__DOT__g_bank__BRA__6__KET____DOT__u_bank__DOT__line_addr;
        CData/*7:0*/ __PVT__u_arrays__DOT__g_bank__BRA__7__KET____DOT__u_bank__DOT__line_addr;
        CData/*7:0*/ __PVT__u_vlsu_hit__DOT__hit_r;
        CData/*2:0*/ __PVT__u_vlsu_miss__DOT__state_q;
        CData/*2:0*/ __PVT__u_vlsu_miss__DOT__state_n;
        CData/*7:0*/ __PVT__u_vlsu_miss__DOT__miss_valid_q;
        CData/*3:0*/ __PVT__u_vlsu_miss__DOT__miss_count_q;
        CData/*3:0*/ __PVT__u_vlsu_miss__DOT__refill_idx_q;
        CData/*7:0*/ __PVT__u_vlsu_miss__DOT__miss_valid_n;
        CData/*3:0*/ __PVT__u_vlsu_miss__DOT__miss_count_n;
        CData/*3:0*/ __PVT__u_vlsu_miss__DOT__refill_idx_n;
        CData/*0:0*/ __PVT__u_vlsu_miss__DOT__is_dup;
        CData/*2:0*/ __PVT__u_plru__DOT__plru_leaf_victim;
        CData/*2:0*/ __PVT__u_plru__DOT__invalid_choice;
        CData/*0:0*/ __PVT__u_plru__DOT__has_invalid;
        CData/*0:0*/ __PVT__u_plru__DOT__d2;
        CData/*0:0*/ __PVT__u_plru__DOT__d1;
        CData/*0:0*/ __PVT__u_plru__DOT__d0;
        CData/*0:0*/ __PVT__u_atomic_alu__DOT__old_less_signed;
        CData/*0:0*/ __PVT__u_atomic_alu__DOT__old_less_unsigned;
        CData/*0:0*/ __PVT__u_atomic_alu__DOT__old_less_signed_dw;
        CData/*0:0*/ __PVT__u_atomic_alu__DOT__old_less_unsigned_dw;
        SData/*15:0*/ __PVT__u_arrays__DOT__bank_state_sel;
        SData/*15:0*/ __PVT__u_arrays__DOT__scalar_state_way_r;
        SData/*15:0*/ u_arrays__DOT____Vcellout__g_bank__BRA__0__KET____DOT__u_bank__state_way_o;
        SData/*15:0*/ u_arrays__DOT____Vcellout__g_bank__BRA__1__KET____DOT__u_bank__state_way_o;
        SData/*15:0*/ u_arrays__DOT____Vcellout__g_bank__BRA__2__KET____DOT__u_bank__state_way_o;
        SData/*15:0*/ u_arrays__DOT____Vcellout__g_bank__BRA__3__KET____DOT__u_bank__state_way_o;
    };
    struct {
        SData/*15:0*/ u_arrays__DOT____Vcellout__g_bank__BRA__4__KET____DOT__u_bank__state_way_o;
        SData/*15:0*/ u_arrays__DOT____Vcellout__g_bank__BRA__5__KET____DOT__u_bank__state_way_o;
        SData/*15:0*/ u_arrays__DOT____Vcellout__g_bank__BRA__6__KET____DOT__u_bank__state_way_o;
        SData/*15:0*/ u_arrays__DOT____Vcellout__g_bank__BRA__7__KET____DOT__u_bank__state_way_o;
        SData/*15:0*/ __PVT__u_arrays__DOT__u_crossbar__DOT__latch_state_q;
        SData/*15:0*/ __PVT__u_arrays__DOT__u_crossbar__DOT__bank_state_r;
        SData/*15:0*/ __PVT__u_vlsu_hit__DOT__state_r;
        VL_INW(vlsu_lane_addr_i,511,0,16);
        VL_INW(vlsu_lane_wdata_i,511,0,16);
        VL_OUTW(__PVT__vlsu_lane_rdata_o,511,0,16);
        VlWide<16>/*511:0*/ __PVT__vlsu_rdata_mux;
        IData/*31:0*/ __PVT__i;
        VlWide<128>/*4095:0*/ __PVT__u_arrays__DOT__bank_rdata_way;
        VlWide<106>/*3391:0*/ __PVT__u_arrays__DOT__bank_tag_way;
        VlWide<4>/*127:0*/ __PVT__u_arrays__DOT__bank_state_way;
        VlWide<16>/*511:0*/ __PVT__u_arrays__DOT__bank_rdata_sel;
        VlWide<14>/*423:0*/ __PVT__u_arrays__DOT__bank_tag_sel;
        VlWide<16>/*511:0*/ __PVT__u_arrays__DOT__scalar_rdata_way_r;
        VlWide<14>/*423:0*/ __PVT__u_arrays__DOT__scalar_tag_way_r;
        VlWide<14>/*423:0*/ u_arrays__DOT____Vcellout__g_bank__BRA__0__KET____DOT__u_bank__tag_way_o;
        VlWide<16>/*511:0*/ u_arrays__DOT____Vcellout__g_bank__BRA__0__KET____DOT__u_bank__rdata_way_o;
        VlWide<14>/*423:0*/ u_arrays__DOT____Vcellout__g_bank__BRA__1__KET____DOT__u_bank__tag_way_o;
        VlWide<16>/*511:0*/ u_arrays__DOT____Vcellout__g_bank__BRA__1__KET____DOT__u_bank__rdata_way_o;
        VlWide<14>/*423:0*/ u_arrays__DOT____Vcellout__g_bank__BRA__2__KET____DOT__u_bank__tag_way_o;
        VlWide<16>/*511:0*/ u_arrays__DOT____Vcellout__g_bank__BRA__2__KET____DOT__u_bank__rdata_way_o;
        VlWide<14>/*423:0*/ u_arrays__DOT____Vcellout__g_bank__BRA__3__KET____DOT__u_bank__tag_way_o;
        VlWide<16>/*511:0*/ u_arrays__DOT____Vcellout__g_bank__BRA__3__KET____DOT__u_bank__rdata_way_o;
        VlWide<14>/*423:0*/ u_arrays__DOT____Vcellout__g_bank__BRA__4__KET____DOT__u_bank__tag_way_o;
        VlWide<16>/*511:0*/ u_arrays__DOT____Vcellout__g_bank__BRA__4__KET____DOT__u_bank__rdata_way_o;
        VlWide<14>/*423:0*/ u_arrays__DOT____Vcellout__g_bank__BRA__5__KET____DOT__u_bank__tag_way_o;
        VlWide<16>/*511:0*/ u_arrays__DOT____Vcellout__g_bank__BRA__5__KET____DOT__u_bank__rdata_way_o;
        VlWide<14>/*423:0*/ u_arrays__DOT____Vcellout__g_bank__BRA__6__KET____DOT__u_bank__tag_way_o;
        VlWide<16>/*511:0*/ u_arrays__DOT____Vcellout__g_bank__BRA__6__KET____DOT__u_bank__rdata_way_o;
        VlWide<14>/*423:0*/ u_arrays__DOT____Vcellout__g_bank__BRA__7__KET____DOT__u_bank__tag_way_o;
        VlWide<16>/*511:0*/ u_arrays__DOT____Vcellout__g_bank__BRA__7__KET____DOT__u_bank__rdata_way_o;
        VlWide<16>/*511:0*/ __PVT__u_arrays__DOT__u_crossbar__DOT__latch_addr_q;
        VlWide<16>/*511:0*/ __PVT__u_arrays__DOT__u_crossbar__DOT__latch_wdata_q;
        IData/*23:0*/ __PVT__u_arrays__DOT__u_crossbar__DOT__latch_way_q;
        VlWide<14>/*423:0*/ __PVT__u_arrays__DOT__u_crossbar__DOT__latch_tag_q;
        IData/*23:0*/ __PVT__u_arrays__DOT__u_crossbar__DOT__bank_word_r;
        IData/*23:0*/ __PVT__u_arrays__DOT__u_crossbar__DOT__bank_way_r;
        VlWide<16>/*511:0*/ __PVT__u_arrays__DOT__u_crossbar__DOT__bank_wdata_r;
        VlWide<14>/*423:0*/ __PVT__u_arrays__DOT__u_crossbar__DOT__bank_tag_r;
        IData/*23:0*/ __PVT__u_arrays__DOT__u_crossbar__DOT__bank_src_lane_r;
        IData/*31:0*/ __PVT__u_arrays__DOT__g_bank__BRA__0__KET____DOT__u_bank__DOT__b;
        IData/*31:0*/ __PVT__u_arrays__DOT__g_bank__BRA__0__KET____DOT__u_bank__DOT__i;
        IData/*31:0*/ __PVT__u_arrays__DOT__g_bank__BRA__0__KET____DOT__u_bank__DOT__j;
        IData/*31:0*/ __PVT__u_arrays__DOT__g_bank__BRA__1__KET____DOT__u_bank__DOT__b;
        IData/*31:0*/ __PVT__u_arrays__DOT__g_bank__BRA__1__KET____DOT__u_bank__DOT__i;
        IData/*31:0*/ __PVT__u_arrays__DOT__g_bank__BRA__1__KET____DOT__u_bank__DOT__j;
        IData/*31:0*/ __PVT__u_arrays__DOT__g_bank__BRA__2__KET____DOT__u_bank__DOT__b;
        IData/*31:0*/ __PVT__u_arrays__DOT__g_bank__BRA__2__KET____DOT__u_bank__DOT__i;
        IData/*31:0*/ __PVT__u_arrays__DOT__g_bank__BRA__2__KET____DOT__u_bank__DOT__j;
        IData/*31:0*/ __PVT__u_arrays__DOT__g_bank__BRA__3__KET____DOT__u_bank__DOT__b;
        IData/*31:0*/ __PVT__u_arrays__DOT__g_bank__BRA__3__KET____DOT__u_bank__DOT__i;
        IData/*31:0*/ __PVT__u_arrays__DOT__g_bank__BRA__3__KET____DOT__u_bank__DOT__j;
        IData/*31:0*/ __PVT__u_arrays__DOT__g_bank__BRA__4__KET____DOT__u_bank__DOT__b;
        IData/*31:0*/ __PVT__u_arrays__DOT__g_bank__BRA__4__KET____DOT__u_bank__DOT__i;
        IData/*31:0*/ __PVT__u_arrays__DOT__g_bank__BRA__4__KET____DOT__u_bank__DOT__j;
        IData/*31:0*/ __PVT__u_arrays__DOT__g_bank__BRA__5__KET____DOT__u_bank__DOT__b;
        IData/*31:0*/ __PVT__u_arrays__DOT__g_bank__BRA__5__KET____DOT__u_bank__DOT__i;
        IData/*31:0*/ __PVT__u_arrays__DOT__g_bank__BRA__5__KET____DOT__u_bank__DOT__j;
        IData/*31:0*/ __PVT__u_arrays__DOT__g_bank__BRA__6__KET____DOT__u_bank__DOT__b;
        IData/*31:0*/ __PVT__u_arrays__DOT__g_bank__BRA__6__KET____DOT__u_bank__DOT__i;
    };
    struct {
        IData/*31:0*/ __PVT__u_arrays__DOT__g_bank__BRA__6__KET____DOT__u_bank__DOT__j;
        IData/*31:0*/ __PVT__u_arrays__DOT__g_bank__BRA__7__KET____DOT__u_bank__DOT__b;
        IData/*31:0*/ __PVT__u_arrays__DOT__g_bank__BRA__7__KET____DOT__u_bank__DOT__i;
        IData/*31:0*/ __PVT__u_arrays__DOT__g_bank__BRA__7__KET____DOT__u_bank__DOT__j;
        IData/*23:0*/ __PVT__u_vlsu_hit__DOT__hit_way_r;
        IData/*31:0*/ __PVT__u_vlsu_miss__DOT__idx;
        IData/*31:0*/ __PVT__u_plru__DOT__si;
        IData/*31:0*/ __PVT__u_atomic_alu__DOT__result_word;
        VL_IN64(addr_i,63,0);
        VL_IN64(wdata_i,63,0);
        VL_OUT64(rdata_o,63,0);
        VL_IN64(vlsu_lane_be_i,63,0);
        VL_OUT64(tl_a_address_o,63,0);
        VL_OUT64(tl_a_data_o,63,0);
        VL_IN64(tl_b_address_i,63,0);
        VL_IN64(tl_b_data_i,63,0);
        VL_OUT64(tl_c_address_o,63,0);
        VL_OUT64(tl_c_data_o,63,0);
        VL_IN64(tl_d_data_i,63,0);
        QData/*63:0*/ __PVT__vlsu_miss_refill_addr;
        QData/*63:0*/ __PVT__amo_old_value_q;
        QData/*63:0*/ __PVT__amo_old_value_n;
        QData/*57:0*/ __PVT__resv_addr_q;
        QData/*57:0*/ __PVT__resv_addr_n;
        QData/*52:0*/ __PVT__pend_tag_q;
        QData/*52:0*/ __PVT__pend_tag_n;
        QData/*63:0*/ __PVT__pend_wdata_q;
        QData/*63:0*/ __PVT__pend_wdata_n;
        QData/*52:0*/ __PVT__pend_evict_tag_q;
        QData/*52:0*/ __PVT__pend_evict_tag_n;
        QData/*63:0*/ __PVT__rdata_beat_q;
        QData/*52:0*/ __PVT__probe_pend_tag_q;
        QData/*52:0*/ __PVT__probe_pend_tag_n;
        QData/*52:0*/ __PVT__binv_tag;
        QData/*52:0*/ __PVT__arr_tag_in;
        QData/*63:0*/ __PVT__arr_wdata;
        QData/*52:0*/ __PVT__tag_slice;
        QData/*63:0*/ __PVT__hit_data_word;
        QData/*63:0*/ __PVT__rdata_n;
        QData/*63:0*/ __PVT__tl_a_address_n;
        QData/*63:0*/ __PVT__tl_c_address_n;
        QData/*63:0*/ __PVT__tl_c_data_n;
        QData/*63:0*/ __PVT__u_arrays__DOT__scalar_rdata_r;
        QData/*52:0*/ __PVT__u_arrays__DOT__scalar_tag_r;
        QData/*63:0*/ __PVT__u_arrays__DOT__u_crossbar__DOT__latch_be_q;
        QData/*39:0*/ __PVT__u_arrays__DOT__u_crossbar__DOT__bank_index_r;
        QData/*63:0*/ __PVT__u_arrays__DOT__u_crossbar__DOT__bank_be_r;
        QData/*52:0*/ u_arrays__DOT__u_crossbar__DOT____Vlvbound_h603b0530__0;
        QData/*63:0*/ __PVT__u_arrays__DOT__g_bank__BRA__0__KET____DOT__u_bank__DOT__be_mask;
        QData/*63:0*/ __PVT__u_arrays__DOT__g_bank__BRA__1__KET____DOT__u_bank__DOT__be_mask;
        QData/*63:0*/ __PVT__u_arrays__DOT__g_bank__BRA__2__KET____DOT__u_bank__DOT__be_mask;
        QData/*63:0*/ __PVT__u_arrays__DOT__g_bank__BRA__3__KET____DOT__u_bank__DOT__be_mask;
        QData/*63:0*/ __PVT__u_arrays__DOT__g_bank__BRA__4__KET____DOT__u_bank__DOT__be_mask;
        QData/*63:0*/ __PVT__u_arrays__DOT__g_bank__BRA__5__KET____DOT__u_bank__DOT__be_mask;
        QData/*63:0*/ __PVT__u_arrays__DOT__g_bank__BRA__6__KET____DOT__u_bank__DOT__be_mask;
        QData/*63:0*/ __PVT__u_arrays__DOT__g_bank__BRA__7__KET____DOT__u_bank__DOT__be_mask;
        QData/*57:0*/ __PVT__u_vlsu_miss__DOT__lane_line_addr;
        QData/*63:0*/ __PVT__u_atomic_alu__DOT__result_dword;
        VlUnpacked<CData/*2:0*/, 8> __PVT__u_arrays__DOT__u_crossbar__DOT__lane_bank;
        VlUnpacked<CData/*4:0*/, 8> __PVT__u_arrays__DOT__u_crossbar__DOT__lane_index;
        VlUnpacked<CData/*2:0*/, 8> __PVT__u_arrays__DOT__u_crossbar__DOT__lane_word;
        VlUnpacked<CData/*7:0*/, 8> __PVT__u_arrays__DOT__u_crossbar__DOT__bank_requesters;
        VlUnpacked<CData/*2:0*/, 8> __PVT__u_arrays__DOT__u_crossbar__DOT__bank_winner;
        VlUnpacked<VlUnpacked<QData/*63:0*/, 256>, 8> __PVT__u_arrays__DOT__g_bank__BRA__0__KET____DOT__u_bank__DOT__data_q;
    };
    struct {
        VlUnpacked<VlUnpacked<QData/*52:0*/, 32>, 8> __PVT__u_arrays__DOT__g_bank__BRA__0__KET____DOT__u_bank__DOT__tag_q;
        VlUnpacked<VlUnpacked<CData/*1:0*/, 32>, 8> __PVT__u_arrays__DOT__g_bank__BRA__0__KET____DOT__u_bank__DOT__state_q;
        VlUnpacked<VlUnpacked<QData/*63:0*/, 256>, 8> __PVT__u_arrays__DOT__g_bank__BRA__1__KET____DOT__u_bank__DOT__data_q;
        VlUnpacked<VlUnpacked<QData/*52:0*/, 32>, 8> __PVT__u_arrays__DOT__g_bank__BRA__1__KET____DOT__u_bank__DOT__tag_q;
        VlUnpacked<VlUnpacked<CData/*1:0*/, 32>, 8> __PVT__u_arrays__DOT__g_bank__BRA__1__KET____DOT__u_bank__DOT__state_q;
        VlUnpacked<VlUnpacked<QData/*63:0*/, 256>, 8> __PVT__u_arrays__DOT__g_bank__BRA__2__KET____DOT__u_bank__DOT__data_q;
        VlUnpacked<VlUnpacked<QData/*52:0*/, 32>, 8> __PVT__u_arrays__DOT__g_bank__BRA__2__KET____DOT__u_bank__DOT__tag_q;
        VlUnpacked<VlUnpacked<CData/*1:0*/, 32>, 8> __PVT__u_arrays__DOT__g_bank__BRA__2__KET____DOT__u_bank__DOT__state_q;
        VlUnpacked<VlUnpacked<QData/*63:0*/, 256>, 8> __PVT__u_arrays__DOT__g_bank__BRA__3__KET____DOT__u_bank__DOT__data_q;
        VlUnpacked<VlUnpacked<QData/*52:0*/, 32>, 8> __PVT__u_arrays__DOT__g_bank__BRA__3__KET____DOT__u_bank__DOT__tag_q;
        VlUnpacked<VlUnpacked<CData/*1:0*/, 32>, 8> __PVT__u_arrays__DOT__g_bank__BRA__3__KET____DOT__u_bank__DOT__state_q;
        VlUnpacked<VlUnpacked<QData/*63:0*/, 256>, 8> __PVT__u_arrays__DOT__g_bank__BRA__4__KET____DOT__u_bank__DOT__data_q;
        VlUnpacked<VlUnpacked<QData/*52:0*/, 32>, 8> __PVT__u_arrays__DOT__g_bank__BRA__4__KET____DOT__u_bank__DOT__tag_q;
        VlUnpacked<VlUnpacked<CData/*1:0*/, 32>, 8> __PVT__u_arrays__DOT__g_bank__BRA__4__KET____DOT__u_bank__DOT__state_q;
        VlUnpacked<VlUnpacked<QData/*63:0*/, 256>, 8> __PVT__u_arrays__DOT__g_bank__BRA__5__KET____DOT__u_bank__DOT__data_q;
        VlUnpacked<VlUnpacked<QData/*52:0*/, 32>, 8> __PVT__u_arrays__DOT__g_bank__BRA__5__KET____DOT__u_bank__DOT__tag_q;
        VlUnpacked<VlUnpacked<CData/*1:0*/, 32>, 8> __PVT__u_arrays__DOT__g_bank__BRA__5__KET____DOT__u_bank__DOT__state_q;
        VlUnpacked<VlUnpacked<QData/*63:0*/, 256>, 8> __PVT__u_arrays__DOT__g_bank__BRA__6__KET____DOT__u_bank__DOT__data_q;
        VlUnpacked<VlUnpacked<QData/*52:0*/, 32>, 8> __PVT__u_arrays__DOT__g_bank__BRA__6__KET____DOT__u_bank__DOT__tag_q;
        VlUnpacked<VlUnpacked<CData/*1:0*/, 32>, 8> __PVT__u_arrays__DOT__g_bank__BRA__6__KET____DOT__u_bank__DOT__state_q;
        VlUnpacked<VlUnpacked<QData/*63:0*/, 256>, 8> __PVT__u_arrays__DOT__g_bank__BRA__7__KET____DOT__u_bank__DOT__data_q;
        VlUnpacked<VlUnpacked<QData/*52:0*/, 32>, 8> __PVT__u_arrays__DOT__g_bank__BRA__7__KET____DOT__u_bank__DOT__tag_q;
        VlUnpacked<VlUnpacked<CData/*1:0*/, 32>, 8> __PVT__u_arrays__DOT__g_bank__BRA__7__KET____DOT__u_bank__DOT__state_q;
        VlUnpacked<QData/*52:0*/, 8> __PVT__u_vlsu_hit__DOT__lane_tag;
        VlUnpacked<CData/*2:0*/, 8> __PVT__u_vlsu_hit__DOT__lane_bank;
        VlUnpacked<VlUnpacked<QData/*52:0*/, 8>, 8> __PVT__u_vlsu_hit__DOT__bank_tags;
        VlUnpacked<VlUnpacked<CData/*1:0*/, 8>, 8> __PVT__u_vlsu_hit__DOT__bank_states;
        VlUnpacked<CData/*7:0*/, 8> __PVT__u_vlsu_hit__DOT__way_match;
        VlUnpacked<QData/*57:0*/, 8> __PVT__u_vlsu_miss__DOT__miss_addr_q;
        VlUnpacked<QData/*57:0*/, 8> __PVT__u_vlsu_miss__DOT__miss_addr_n;
        VlUnpacked<CData/*6:0*/, 32> __PVT__u_plru__DOT__plru_bits_q;
    };

    // INTERNAL VARIABLES
    Vrv64g_cache_system_tb__Syms* const vlSymsp;

    // CONSTRUCTORS
    Vrv64g_cache_system_tb_rv64g_l1_dcache(Vrv64g_cache_system_tb__Syms* symsp, const char* v__name);
    ~Vrv64g_cache_system_tb_rv64g_l1_dcache();
    VL_UNCOPYABLE(Vrv64g_cache_system_tb_rv64g_l1_dcache);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
};


#endif  // guard
